name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    
    - name: Set up Arduino CLI
      uses: arduino/setup-arduino-cli@v1
    
    - name: Install platform
      run: |
        arduino-cli core update-index
        arduino-cli core install arduino:avr
        arduino-cli lib install LiquidCrystal
      
    - name: Compile Sketch
      run: arduino-cli compile -b arduino:avr:leonardo --warnings "default"
